
package net.java.antlrjavaparser;


import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.antlr.v4.runtime.tree.ErrorNode;

public class Java7ParserBaseListener implements Java7ParserListener {
	@Override public void enterInnerCreator(Java7Parser.InnerCreatorContext ctx) { }
	@Override public void exitInnerCreator(Java7Parser.InnerCreatorContext ctx) { }
	@Override public void enterExpressionList(Java7Parser.ExpressionListContext ctx) { }
	@Override public void exitExpressionList(Java7Parser.ExpressionListContext ctx) { }
	@Override public void enterTypeDeclaration(Java7Parser.TypeDeclarationContext ctx) { }
	@Override public void exitTypeDeclaration(Java7Parser.TypeDeclarationContext ctx) { }
	@Override public void enterAnnotation(Java7Parser.AnnotationContext ctx) { }
	@Override public void exitAnnotation(Java7Parser.AnnotationContext ctx) { }
	@Override public void enterEnumConstant(Java7Parser.EnumConstantContext ctx) { }
	@Override public void exitEnumConstant(Java7Parser.EnumConstantContext ctx) { }
	@Override public void enterSwitchBlockStatementGroups(Java7Parser.SwitchBlockStatementGroupsContext ctx) { }
	@Override public void exitSwitchBlockStatementGroups(Java7Parser.SwitchBlockStatementGroupsContext ctx) { }
	@Override public void enterAnnotationHeader(Java7Parser.AnnotationHeaderContext ctx) { }
	@Override public void exitAnnotationHeader(Java7Parser.AnnotationHeaderContext ctx) { }
	@Override public void enterNormalClassDeclaration(Java7Parser.NormalClassDeclarationContext ctx) { }
	@Override public void exitNormalClassDeclaration(Java7Parser.NormalClassDeclarationContext ctx) { }
	@Override public void enterImportDeclaration(Java7Parser.ImportDeclarationContext ctx) { }
	@Override public void exitImportDeclaration(Java7Parser.ImportDeclarationContext ctx) { }
	@Override public void enterElementValuePairs(Java7Parser.ElementValuePairsContext ctx) { }
	@Override public void exitElementValuePairs(Java7Parser.ElementValuePairsContext ctx) { }
	@Override public void enterInterfaceMethodDeclaration(Java7Parser.InterfaceMethodDeclarationContext ctx) { }
	@Override public void exitInterfaceMethodDeclaration(Java7Parser.InterfaceMethodDeclarationContext ctx) { }
	@Override public void enterExclusiveOrExpression(Java7Parser.ExclusiveOrExpressionContext ctx) { }
	@Override public void exitExclusiveOrExpression(Java7Parser.ExclusiveOrExpressionContext ctx) { }
	@Override public void enterInstanceOfExpression(Java7Parser.InstanceOfExpressionContext ctx) { }
	@Override public void exitInstanceOfExpression(Java7Parser.InstanceOfExpressionContext ctx) { }
	@Override public void enterInterfaceBodyDeclaration(Java7Parser.InterfaceBodyDeclarationContext ctx) { }
	@Override public void exitInterfaceBodyDeclaration(Java7Parser.InterfaceBodyDeclarationContext ctx) { }
	@Override public void enterEnumConstants(Java7Parser.EnumConstantsContext ctx) { }
	@Override public void exitEnumConstants(Java7Parser.EnumConstantsContext ctx) { }
	@Override public void enterMarkerAnnotation(Java7Parser.MarkerAnnotationContext ctx) { }
	@Override public void exitMarkerAnnotation(Java7Parser.MarkerAnnotationContext ctx) { }
	@Override public void enterCatchClause(Java7Parser.CatchClauseContext ctx) { }
	@Override public void exitCatchClause(Java7Parser.CatchClauseContext ctx) { }
	@Override public void enterTryWithResources(Java7Parser.TryWithResourcesContext ctx) { }
	@Override public void exitTryWithResources(Java7Parser.TryWithResourcesContext ctx) { }
	@Override public void enterSingleElementAnnotation(Java7Parser.SingleElementAnnotationContext ctx) { }
	@Override public void exitSingleElementAnnotation(Java7Parser.SingleElementAnnotationContext ctx) { }
	@Override public void enterEnumBody(Java7Parser.EnumBodyContext ctx) { }
	@Override public void exitEnumBody(Java7Parser.EnumBodyContext ctx) { }
	@Override public void enterEnumDeclaration(Java7Parser.EnumDeclarationContext ctx) { }
	@Override public void exitEnumDeclaration(Java7Parser.EnumDeclarationContext ctx) { }
	@Override public void enterQualifiedImportName(Java7Parser.QualifiedImportNameContext ctx) { }
	@Override public void exitQualifiedImportName(Java7Parser.QualifiedImportNameContext ctx) { }
	@Override public void enterTypeParameter(Java7Parser.TypeParameterContext ctx) { }
	@Override public void exitTypeParameter(Java7Parser.TypeParameterContext ctx) { }
	@Override public void enterExplicitConstructorInvocation(Java7Parser.ExplicitConstructorInvocationContext ctx) { }
	@Override public void exitExplicitConstructorInvocation(Java7Parser.ExplicitConstructorInvocationContext ctx) { }
	@Override public void enterEnumBodyDeclarations(Java7Parser.EnumBodyDeclarationsContext ctx) { }
	@Override public void exitEnumBodyDeclarations(Java7Parser.EnumBodyDeclarationsContext ctx) { }
	@Override public void enterTypeBound(Java7Parser.TypeBoundContext ctx) { }
	@Override public void exitTypeBound(Java7Parser.TypeBoundContext ctx) { }
	@Override public void enterAnnotationMethodDeclaration(Java7Parser.AnnotationMethodDeclarationContext ctx) { }
	@Override public void exitAnnotationMethodDeclaration(Java7Parser.AnnotationMethodDeclarationContext ctx) { }
	@Override public void enterVariableInitializer(Java7Parser.VariableInitializerContext ctx) { }
	@Override public void exitVariableInitializer(Java7Parser.VariableInitializerContext ctx) { }
	@Override public void enterBlock(Java7Parser.BlockContext ctx) { }
	@Override public void exitBlock(Java7Parser.BlockContext ctx) { }
	@Override public void enterConditionalExpression(Java7Parser.ConditionalExpressionContext ctx) { }
	@Override public void exitConditionalExpression(Java7Parser.ConditionalExpressionContext ctx) { }
	@Override public void enterAndExpression(Java7Parser.AndExpressionContext ctx) { }
	@Override public void exitAndExpression(Java7Parser.AndExpressionContext ctx) { }
	@Override public void enterLocalVariableDeclarationStatement(Java7Parser.LocalVariableDeclarationStatementContext ctx) { }
	@Override public void exitLocalVariableDeclarationStatement(Java7Parser.LocalVariableDeclarationStatementContext ctx) { }
	@Override public void enterSuperSuffix(Java7Parser.SuperSuffixContext ctx) { }
	@Override public void exitSuperSuffix(Java7Parser.SuperSuffixContext ctx) { }
	@Override public void enterFieldDeclaration(Java7Parser.FieldDeclarationContext ctx) { }
	@Override public void exitFieldDeclaration(Java7Parser.FieldDeclarationContext ctx) { }
	@Override public void enterNormalInterfaceDeclaration(Java7Parser.NormalInterfaceDeclarationContext ctx) { }
	@Override public void exitNormalInterfaceDeclaration(Java7Parser.NormalInterfaceDeclarationContext ctx) { }
	@Override public void enterModifiers(Java7Parser.ModifiersContext ctx) { }
	@Override public void exitModifiers(Java7Parser.ModifiersContext ctx) { }
	@Override public void enterTypeHeader(Java7Parser.TypeHeaderContext ctx) { }
	@Override public void exitTypeHeader(Java7Parser.TypeHeaderContext ctx) { }
	@Override public void enterParExpression(Java7Parser.ParExpressionContext ctx) { }
	@Override public void exitParExpression(Java7Parser.ParExpressionContext ctx) { }
	@Override public void enterCatches(Java7Parser.CatchesContext ctx) { }
	@Override public void exitCatches(Java7Parser.CatchesContext ctx) { }
	@Override public void enterSwitchLabel(Java7Parser.SwitchLabelContext ctx) { }
	@Override public void exitSwitchLabel(Java7Parser.SwitchLabelContext ctx) { }
	@Override public void enterTypeParameters(Java7Parser.TypeParametersContext ctx) { }
	@Override public void exitTypeParameters(Java7Parser.TypeParametersContext ctx) { }
	@Override public void enterQualifiedName(Java7Parser.QualifiedNameContext ctx) { }
	@Override public void exitQualifiedName(Java7Parser.QualifiedNameContext ctx) { }
	@Override public void enterClassDeclaration(Java7Parser.ClassDeclarationContext ctx) { }
	@Override public void exitClassDeclaration(Java7Parser.ClassDeclarationContext ctx) { }
	@Override public void enterLocalVariableHeader(Java7Parser.LocalVariableHeaderContext ctx) { }
	@Override public void exitLocalVariableHeader(Java7Parser.LocalVariableHeaderContext ctx) { }
	@Override public void enterTrystatement(Java7Parser.TrystatementContext ctx) { }
	@Override public void exitTrystatement(Java7Parser.TrystatementContext ctx) { }
	@Override public void enterInclusiveOrExpression(Java7Parser.InclusiveOrExpressionContext ctx) { }
	@Override public void exitInclusiveOrExpression(Java7Parser.InclusiveOrExpressionContext ctx) { }
	@Override public void enterArguments(Java7Parser.ArgumentsContext ctx) { }
	@Override public void exitArguments(Java7Parser.ArgumentsContext ctx) { }
	@Override public void enterEqualityExpression(Java7Parser.EqualityExpressionContext ctx) { }
	@Override public void exitEqualityExpression(Java7Parser.EqualityExpressionContext ctx) { }
	@Override public void enterFormalParameters(Java7Parser.FormalParametersContext ctx) { }
	@Override public void exitFormalParameters(Java7Parser.FormalParametersContext ctx) { }
	@Override public void enterCastExpression(Java7Parser.CastExpressionContext ctx) { }
	@Override public void exitCastExpression(Java7Parser.CastExpressionContext ctx) { }
	@Override public void enterInterfaceHeader(Java7Parser.InterfaceHeaderContext ctx) { }
	@Override public void exitInterfaceHeader(Java7Parser.InterfaceHeaderContext ctx) { }
	@Override public void enterTypeArgument(Java7Parser.TypeArgumentContext ctx) { }
	@Override public void exitTypeArgument(Java7Parser.TypeArgumentContext ctx) { }
	@Override public void enterAnnotations(Java7Parser.AnnotationsContext ctx) { }
	@Override public void exitAnnotations(Java7Parser.AnnotationsContext ctx) { }
	@Override public void enterForInit(Java7Parser.ForInitContext ctx) { }
	@Override public void exitForInit(Java7Parser.ForInitContext ctx) { }
	@Override public void enterSelector(Java7Parser.SelectorContext ctx) { }
	@Override public void exitSelector(Java7Parser.SelectorContext ctx) { }
	@Override public void enterVariableDeclarator(Java7Parser.VariableDeclaratorContext ctx) { }
	@Override public void exitVariableDeclarator(Java7Parser.VariableDeclaratorContext ctx) { }
	@Override public void enterAnnotationTypeDeclaration(Java7Parser.AnnotationTypeDeclarationContext ctx) { }
	@Override public void exitAnnotationTypeDeclaration(Java7Parser.AnnotationTypeDeclarationContext ctx) { }
	@Override public void enterExpression(Java7Parser.ExpressionContext ctx) { }
	@Override public void exitExpression(Java7Parser.ExpressionContext ctx) { }
	@Override public void enterResources(Java7Parser.ResourcesContext ctx) { }
	@Override public void exitResources(Java7Parser.ResourcesContext ctx) { }
	@Override public void enterRelationalOp(Java7Parser.RelationalOpContext ctx) { }
	@Override public void exitRelationalOp(Java7Parser.RelationalOpContext ctx) { }
	@Override public void enterFormalParameter(Java7Parser.FormalParameterContext ctx) { }
	@Override public void exitFormalParameter(Java7Parser.FormalParameterContext ctx) { }
	@Override public void enterUnaryExpression(Java7Parser.UnaryExpressionContext ctx) { }
	@Override public void exitUnaryExpression(Java7Parser.UnaryExpressionContext ctx) { }
	@Override public void enterType(Java7Parser.TypeContext ctx) { }
	@Override public void exitType(Java7Parser.TypeContext ctx) { }
	@Override public void enterInterfaceFieldDeclaration(Java7Parser.InterfaceFieldDeclarationContext ctx) { }
	@Override public void exitInterfaceFieldDeclaration(Java7Parser.InterfaceFieldDeclarationContext ctx) { }
	@Override public void enterMemberDecl(Java7Parser.MemberDeclContext ctx) { }
	@Override public void exitMemberDecl(Java7Parser.MemberDeclContext ctx) { }
	@Override public void enterElementValueArrayInitializer(Java7Parser.ElementValueArrayInitializerContext ctx) { }
	@Override public void exitElementValueArrayInitializer(Java7Parser.ElementValueArrayInitializerContext ctx) { }
	@Override public void enterClassHeader(Java7Parser.ClassHeaderContext ctx) { }
	@Override public void exitClassHeader(Java7Parser.ClassHeaderContext ctx) { }
	@Override public void enterPrimary(Java7Parser.PrimaryContext ctx) { }
	@Override public void exitPrimary(Java7Parser.PrimaryContext ctx) { }
	@Override public void enterEllipsisParameterDecl(Java7Parser.EllipsisParameterDeclContext ctx) { }
	@Override public void exitEllipsisParameterDecl(Java7Parser.EllipsisParameterDeclContext ctx) { }
	@Override public void enterNormalParameterDecl(Java7Parser.NormalParameterDeclContext ctx) { }
	@Override public void exitNormalParameterDecl(Java7Parser.NormalParameterDeclContext ctx) { }
	@Override public void enterShiftExpression(Java7Parser.ShiftExpressionContext ctx) { }
	@Override public void exitShiftExpression(Java7Parser.ShiftExpressionContext ctx) { }
	@Override public void enterIdentifierSuffix(Java7Parser.IdentifierSuffixContext ctx) { }
	@Override public void exitIdentifierSuffix(Java7Parser.IdentifierSuffixContext ctx) { }
	@Override public void enterClassBody(Java7Parser.ClassBodyContext ctx) { }
	@Override public void exitClassBody(Java7Parser.ClassBodyContext ctx) { }
	@Override public void enterConstructorBlock(Java7Parser.ConstructorBlockContext ctx) { }
	@Override public void exitConstructorBlock(Java7Parser.ConstructorBlockContext ctx) { }
	@Override public void enterCreatedName(Java7Parser.CreatedNameContext ctx) { }
	@Override public void exitCreatedName(Java7Parser.CreatedNameContext ctx) { }
	@Override public void enterInterfaceDeclaration(Java7Parser.InterfaceDeclarationContext ctx) { }
	@Override public void exitInterfaceDeclaration(Java7Parser.InterfaceDeclarationContext ctx) { }
	@Override public void enterPackageDeclaration(Java7Parser.PackageDeclarationContext ctx) { }
	@Override public void exitPackageDeclaration(Java7Parser.PackageDeclarationContext ctx) { }
	@Override public void enterConditionalAndExpression(Java7Parser.ConditionalAndExpressionContext ctx) { }
	@Override public void exitConditionalAndExpression(Java7Parser.ConditionalAndExpressionContext ctx) { }
	@Override public void enterAdditiveExpression(Java7Parser.AdditiveExpressionContext ctx) { }
	@Override public void exitAdditiveExpression(Java7Parser.AdditiveExpressionContext ctx) { }
	@Override public void enterTypeArguments(Java7Parser.TypeArgumentsContext ctx) { }
	@Override public void exitTypeArguments(Java7Parser.TypeArgumentsContext ctx) { }
	@Override public void enterClassCreatorRest(Java7Parser.ClassCreatorRestContext ctx) { }
	@Override public void exitClassCreatorRest(Java7Parser.ClassCreatorRestContext ctx) { }
	@Override public void enterArrayCreator(Java7Parser.ArrayCreatorContext ctx) { }
	@Override public void exitArrayCreator(Java7Parser.ArrayCreatorContext ctx) { }
	@Override public void enterCatchFormalParameter(Java7Parser.CatchFormalParameterContext ctx) { }
	@Override public void exitCatchFormalParameter(Java7Parser.CatchFormalParameterContext ctx) { }
	@Override public void enterModifier(Java7Parser.ModifierContext ctx) { }
	@Override public void exitModifier(Java7Parser.ModifierContext ctx) { }
	@Override public void enterStatement(Java7Parser.StatementContext ctx) { }
	@Override public void exitStatement(Java7Parser.StatementContext ctx) { }
	@Override public void enterInterfaceBody(Java7Parser.InterfaceBodyContext ctx) { }
	@Override public void exitInterfaceBody(Java7Parser.InterfaceBodyContext ctx) { }
	@Override public void enterClassBodyDeclaration(Java7Parser.ClassBodyDeclarationContext ctx) { }
	@Override public void exitClassBodyDeclaration(Java7Parser.ClassBodyDeclarationContext ctx) { }
	@Override public void enterTypeList(Java7Parser.TypeListContext ctx) { }
	@Override public void exitTypeList(Java7Parser.TypeListContext ctx) { }
	@Override public void enterLocalVariableDeclaration(Java7Parser.LocalVariableDeclarationContext ctx) { }
	@Override public void exitLocalVariableDeclaration(Java7Parser.LocalVariableDeclarationContext ctx) { }
	@Override public void enterMultiplicativeExpression(Java7Parser.MultiplicativeExpressionContext ctx) { }
	@Override public void exitMultiplicativeExpression(Java7Parser.MultiplicativeExpressionContext ctx) { }
	@Override public void enterAssignmentOperator(Java7Parser.AssignmentOperatorContext ctx) { }
	@Override public void exitAssignmentOperator(Java7Parser.AssignmentOperatorContext ctx) { }
	@Override public void enterCompilationUnit(Java7Parser.CompilationUnitContext ctx) { }
	@Override public void exitCompilationUnit(Java7Parser.CompilationUnitContext ctx) { }
	@Override public void enterElementValue(Java7Parser.ElementValueContext ctx) { }
	@Override public void exitElementValue(Java7Parser.ElementValueContext ctx) { }
	@Override public void enterShiftOp(Java7Parser.ShiftOpContext ctx) { }
	@Override public void exitShiftOp(Java7Parser.ShiftOpContext ctx) { }
	@Override public void enterClassOrInterfaceType(Java7Parser.ClassOrInterfaceTypeContext ctx) { }
	@Override public void exitClassOrInterfaceType(Java7Parser.ClassOrInterfaceTypeContext ctx) { }
	@Override public void enterUnaryExpressionNotPlusMinus(Java7Parser.UnaryExpressionNotPlusMinusContext ctx) { }
	@Override public void exitUnaryExpressionNotPlusMinus(Java7Parser.UnaryExpressionNotPlusMinusContext ctx) { }
	@Override public void enterAnnotationTypeElementDeclaration(Java7Parser.AnnotationTypeElementDeclarationContext ctx) { }
	@Override public void exitAnnotationTypeElementDeclaration(Java7Parser.AnnotationTypeElementDeclarationContext ctx) { }
	@Override public void enterBlockStatement(Java7Parser.BlockStatementContext ctx) { }
	@Override public void exitBlockStatement(Java7Parser.BlockStatementContext ctx) { }
	@Override public void enterAnnotationTypeBody(Java7Parser.AnnotationTypeBodyContext ctx) { }
	@Override public void exitAnnotationTypeBody(Java7Parser.AnnotationTypeBodyContext ctx) { }
	@Override public void enterCreator(Java7Parser.CreatorContext ctx) { }
	@Override public void exitCreator(Java7Parser.CreatorContext ctx) { }
	@Override public void enterQualifiedNameList(Java7Parser.QualifiedNameListContext ctx) { }
	@Override public void exitQualifiedNameList(Java7Parser.QualifiedNameListContext ctx) { }
	@Override public void enterFormalParameterDecls(Java7Parser.FormalParameterDeclsContext ctx) { }
	@Override public void exitFormalParameterDecls(Java7Parser.FormalParameterDeclsContext ctx) { }
	@Override public void enterNormalAnnotation(Java7Parser.NormalAnnotationContext ctx) { }
	@Override public void exitNormalAnnotation(Java7Parser.NormalAnnotationContext ctx) { }
	@Override public void enterRelationalExpression(Java7Parser.RelationalExpressionContext ctx) { }
	@Override public void exitRelationalExpression(Java7Parser.RelationalExpressionContext ctx) { }
	@Override public void enterConditionalOrExpression(Java7Parser.ConditionalOrExpressionContext ctx) { }
	@Override public void exitConditionalOrExpression(Java7Parser.ConditionalOrExpressionContext ctx) { }
	@Override public void enterForstatement(Java7Parser.ForstatementContext ctx) { }
	@Override public void exitForstatement(Java7Parser.ForstatementContext ctx) { }
	@Override public void enterIdentifierTypeArgument(Java7Parser.IdentifierTypeArgumentContext ctx) { }
	@Override public void exitIdentifierTypeArgument(Java7Parser.IdentifierTypeArgumentContext ctx) { }
	@Override public void enterEnumHeader(Java7Parser.EnumHeaderContext ctx) { }
	@Override public void exitEnumHeader(Java7Parser.EnumHeaderContext ctx) { }
	@Override public void enterMethodDeclaration(Java7Parser.MethodDeclarationContext ctx) { }
	@Override public void exitMethodDeclaration(Java7Parser.MethodDeclarationContext ctx) { }
	@Override public void enterResourceSpecification(Java7Parser.ResourceSpecificationContext ctx) { }
	@Override public void exitResourceSpecification(Java7Parser.ResourceSpecificationContext ctx) { }
	@Override public void enterConstructorDeclaration(Java7Parser.ConstructorDeclarationContext ctx) { }
	@Override public void exitConstructorDeclaration(Java7Parser.ConstructorDeclarationContext ctx) { }
	@Override public void enterResource(Java7Parser.ResourceContext ctx) { }
	@Override public void exitResource(Java7Parser.ResourceContext ctx) { }
	@Override public void enterElementValuePair(Java7Parser.ElementValuePairContext ctx) { }
	@Override public void exitElementValuePair(Java7Parser.ElementValuePairContext ctx) { }
	@Override public void enterMethodHeader(Java7Parser.MethodHeaderContext ctx) { }
	@Override public void exitMethodHeader(Java7Parser.MethodHeaderContext ctx) { }
	@Override public void enterArrayInitializer(Java7Parser.ArrayInitializerContext ctx) { }
	@Override public void exitArrayInitializer(Java7Parser.ArrayInitializerContext ctx) { }
	@Override public void enterPrimitiveType(Java7Parser.PrimitiveTypeContext ctx) { }
	@Override public void exitPrimitiveType(Java7Parser.PrimitiveTypeContext ctx) { }
	@Override public void enterVariableModifiers(Java7Parser.VariableModifiersContext ctx) { }
	@Override public void exitVariableModifiers(Java7Parser.VariableModifiersContext ctx) { }
	@Override public void enterNonWildcardTypeArguments(Java7Parser.NonWildcardTypeArgumentsContext ctx) { }
	@Override public void exitNonWildcardTypeArguments(Java7Parser.NonWildcardTypeArgumentsContext ctx) { }
	@Override public void enterFieldHeader(Java7Parser.FieldHeaderContext ctx) { }
	@Override public void exitFieldHeader(Java7Parser.FieldHeaderContext ctx) { }
	@Override public void enterClassOrInterfaceDeclaration(Java7Parser.ClassOrInterfaceDeclarationContext ctx) { }
	@Override public void exitClassOrInterfaceDeclaration(Java7Parser.ClassOrInterfaceDeclarationContext ctx) { }
	@Override public void enterLiteral(Java7Parser.LiteralContext ctx) { }
	@Override public void exitLiteral(Java7Parser.LiteralContext ctx) { }
	@Override public void enterSwitchBlockStatementGroup(Java7Parser.SwitchBlockStatementGroupContext ctx) { }
	@Override public void exitSwitchBlockStatementGroup(Java7Parser.SwitchBlockStatementGroupContext ctx) { }

	@Override public void enterEveryRule(ParserRuleContext ctx) { }
	@Override public void exitEveryRule(ParserRuleContext ctx) { }
	@Override public void visitTerminal(TerminalNode node) { }
	@Override public void visitErrorNode(ErrorNode node) { }
}