
package net.java.antlrjavaparser;


import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.antlr.v4.runtime.tree.ErrorNode;

public class Java7BaseListener implements Java7Listener {
	@Override public void enterInnerCreator(Java7Parser.InnerCreatorContext ctx) { }
	@Override public void exitInnerCreator(Java7Parser.InnerCreatorContext ctx) { }
	@Override public void enterMethodOrFieldDecl(Java7Parser.MethodOrFieldDeclContext ctx) { }
	@Override public void exitMethodOrFieldDecl(Java7Parser.MethodOrFieldDeclContext ctx) { }
	@Override public void enterExpressionList(Java7Parser.ExpressionListContext ctx) { }
	@Override public void exitExpressionList(Java7Parser.ExpressionListContext ctx) { }
	@Override public void enterFieldDeclaratorsRest(Java7Parser.FieldDeclaratorsRestContext ctx) { }
	@Override public void exitFieldDeclaratorsRest(Java7Parser.FieldDeclaratorsRestContext ctx) { }
	@Override public void enterTypeDeclaration(Java7Parser.TypeDeclarationContext ctx) { }
	@Override public void exitTypeDeclaration(Java7Parser.TypeDeclarationContext ctx) { }
	@Override public void enterForUpdate(Java7Parser.ForUpdateContext ctx) { }
	@Override public void exitForUpdate(Java7Parser.ForUpdateContext ctx) { }
	@Override public void enterAnnotation(Java7Parser.AnnotationContext ctx) { }
	@Override public void exitAnnotation(Java7Parser.AnnotationContext ctx) { }
	@Override public void enterEnumConstant(Java7Parser.EnumConstantContext ctx) { }
	@Override public void exitEnumConstant(Java7Parser.EnumConstantContext ctx) { }
	@Override public void enterSwitchBlockStatementGroups(Java7Parser.SwitchBlockStatementGroupsContext ctx) { }
	@Override public void exitSwitchBlockStatementGroups(Java7Parser.SwitchBlockStatementGroupsContext ctx) { }
	@Override public void enterNormalClassDeclaration(Java7Parser.NormalClassDeclarationContext ctx) { }
	@Override public void exitNormalClassDeclaration(Java7Parser.NormalClassDeclarationContext ctx) { }
	@Override public void enterAnnotationMethodOrConstantRest(Java7Parser.AnnotationMethodOrConstantRestContext ctx) { }
	@Override public void exitAnnotationMethodOrConstantRest(Java7Parser.AnnotationMethodOrConstantRestContext ctx) { }
	@Override public void enterImportDeclaration(Java7Parser.ImportDeclarationContext ctx) { }
	@Override public void exitImportDeclaration(Java7Parser.ImportDeclarationContext ctx) { }
	@Override public void enterEnumConstantName(Java7Parser.EnumConstantNameContext ctx) { }
	@Override public void exitEnumConstantName(Java7Parser.EnumConstantNameContext ctx) { }
	@Override public void enterQualifiedIdentifierList(Java7Parser.QualifiedIdentifierListContext ctx) { }
	@Override public void exitQualifiedIdentifierList(Java7Parser.QualifiedIdentifierListContext ctx) { }
	@Override public void enterElementValuePairs(Java7Parser.ElementValuePairsContext ctx) { }
	@Override public void exitElementValuePairs(Java7Parser.ElementValuePairsContext ctx) { }
	@Override public void enterVariableDeclarators(Java7Parser.VariableDeclaratorsContext ctx) { }
	@Override public void exitVariableDeclarators(Java7Parser.VariableDeclaratorsContext ctx) { }
	@Override public void enterMethodDeclaratorRest(Java7Parser.MethodDeclaratorRestContext ctx) { }
	@Override public void exitMethodDeclaratorRest(Java7Parser.MethodDeclaratorRestContext ctx) { }
	@Override public void enterInterfaceBodyDeclaration(Java7Parser.InterfaceBodyDeclarationContext ctx) { }
	@Override public void exitInterfaceBodyDeclaration(Java7Parser.InterfaceBodyDeclarationContext ctx) { }
	@Override public void enterEnumConstants(Java7Parser.EnumConstantsContext ctx) { }
	@Override public void exitEnumConstants(Java7Parser.EnumConstantsContext ctx) { }
	@Override public void enterCatchClause(Java7Parser.CatchClauseContext ctx) { }
	@Override public void exitCatchClause(Java7Parser.CatchClauseContext ctx) { }
	@Override public void enterEnumBody(Java7Parser.EnumBodyContext ctx) { }
	@Override public void exitEnumBody(Java7Parser.EnumBodyContext ctx) { }
	@Override public void enterEnumDeclaration(Java7Parser.EnumDeclarationContext ctx) { }
	@Override public void exitEnumDeclaration(Java7Parser.EnumDeclarationContext ctx) { }
	@Override public void enterExplicitGenericInvocationSuffix(Java7Parser.ExplicitGenericInvocationSuffixContext ctx) { }
	@Override public void exitExplicitGenericInvocationSuffix(Java7Parser.ExplicitGenericInvocationSuffixContext ctx) { }
	@Override public void enterTypeParameter(Java7Parser.TypeParameterContext ctx) { }
	@Override public void exitTypeParameter(Java7Parser.TypeParameterContext ctx) { }
	@Override public void enterEnumBodyDeclarations(Java7Parser.EnumBodyDeclarationsContext ctx) { }
	@Override public void exitEnumBodyDeclarations(Java7Parser.EnumBodyDeclarationsContext ctx) { }
	@Override public void enterInterfaceMethodDeclaratorRest(Java7Parser.InterfaceMethodDeclaratorRestContext ctx) { }
	@Override public void exitInterfaceMethodDeclaratorRest(Java7Parser.InterfaceMethodDeclaratorRestContext ctx) { }
	@Override public void enterStatementExpression(Java7Parser.StatementExpressionContext ctx) { }
	@Override public void exitStatementExpression(Java7Parser.StatementExpressionContext ctx) { }
	@Override public void enterFinallyRule(Java7Parser.FinallyRuleContext ctx) { }
	@Override public void exitFinallyRule(Java7Parser.FinallyRuleContext ctx) { }
	@Override public void enterVariableInitializer(Java7Parser.VariableInitializerContext ctx) { }
	@Override public void exitVariableInitializer(Java7Parser.VariableInitializerContext ctx) { }
	@Override public void enterBlock(Java7Parser.BlockContext ctx) { }
	@Override public void exitBlock(Java7Parser.BlockContext ctx) { }
	@Override public void enterConstantDeclaratorsRest(Java7Parser.ConstantDeclaratorsRestContext ctx) { }
	@Override public void exitConstantDeclaratorsRest(Java7Parser.ConstantDeclaratorsRestContext ctx) { }
	@Override public void enterInterfaceMethodOrFieldDecl(Java7Parser.InterfaceMethodOrFieldDeclContext ctx) { }
	@Override public void exitInterfaceMethodOrFieldDecl(Java7Parser.InterfaceMethodOrFieldDeclContext ctx) { }
	@Override public void enterLocalVariableDeclarationStatement(Java7Parser.LocalVariableDeclarationStatementContext ctx) { }
	@Override public void exitLocalVariableDeclarationStatement(Java7Parser.LocalVariableDeclarationStatementContext ctx) { }
	@Override public void enterSuperSuffix(Java7Parser.SuperSuffixContext ctx) { }
	@Override public void exitSuperSuffix(Java7Parser.SuperSuffixContext ctx) { }
	@Override public void enterForVarControl(Java7Parser.ForVarControlContext ctx) { }
	@Override public void exitForVarControl(Java7Parser.ForVarControlContext ctx) { }
	@Override public void enterNormalInterfaceDeclaration(Java7Parser.NormalInterfaceDeclarationContext ctx) { }
	@Override public void exitNormalInterfaceDeclaration(Java7Parser.NormalInterfaceDeclarationContext ctx) { }
	@Override public void enterExplicitGenericInvocation(Java7Parser.ExplicitGenericInvocationContext ctx) { }
	@Override public void exitExplicitGenericInvocation(Java7Parser.ExplicitGenericInvocationContext ctx) { }
	@Override public void enterElementValues(Java7Parser.ElementValuesContext ctx) { }
	@Override public void exitElementValues(Java7Parser.ElementValuesContext ctx) { }
	@Override public void enterParExpression(Java7Parser.ParExpressionContext ctx) { }
	@Override public void exitParExpression(Java7Parser.ParExpressionContext ctx) { }
	@Override public void enterCatches(Java7Parser.CatchesContext ctx) { }
	@Override public void exitCatches(Java7Parser.CatchesContext ctx) { }
	@Override public void enterSwitchLabel(Java7Parser.SwitchLabelContext ctx) { }
	@Override public void exitSwitchLabel(Java7Parser.SwitchLabelContext ctx) { }
	@Override public void enterTypeParameters(Java7Parser.TypeParametersContext ctx) { }
	@Override public void exitTypeParameters(Java7Parser.TypeParametersContext ctx) { }
	@Override public void enterClassDeclaration(Java7Parser.ClassDeclarationContext ctx) { }
	@Override public void exitClassDeclaration(Java7Parser.ClassDeclarationContext ctx) { }
	@Override public void enterBooleanLiteral(Java7Parser.BooleanLiteralContext ctx) { }
	@Override public void exitBooleanLiteral(Java7Parser.BooleanLiteralContext ctx) { }
	@Override public void enterGenericMethodOrConstructorDecl(Java7Parser.GenericMethodOrConstructorDeclContext ctx) { }
	@Override public void exitGenericMethodOrConstructorDecl(Java7Parser.GenericMethodOrConstructorDeclContext ctx) { }
	@Override public void enterTypeName(Java7Parser.TypeNameContext ctx) { }
	@Override public void exitTypeName(Java7Parser.TypeNameContext ctx) { }
	@Override public void enterArguments(Java7Parser.ArgumentsContext ctx) { }
	@Override public void exitArguments(Java7Parser.ArgumentsContext ctx) { }
	@Override public void enterFormalParameters(Java7Parser.FormalParametersContext ctx) { }
	@Override public void exitFormalParameters(Java7Parser.FormalParametersContext ctx) { }
	@Override public void enterTypeArgument(Java7Parser.TypeArgumentContext ctx) { }
	@Override public void exitTypeArgument(Java7Parser.TypeArgumentContext ctx) { }
	@Override public void enterConstructorDeclaratorRest(Java7Parser.ConstructorDeclaratorRestContext ctx) { }
	@Override public void exitConstructorDeclaratorRest(Java7Parser.ConstructorDeclaratorRestContext ctx) { }
	@Override public void enterAnnotations(Java7Parser.AnnotationsContext ctx) { }
	@Override public void exitAnnotations(Java7Parser.AnnotationsContext ctx) { }
	@Override public void enterForInit(Java7Parser.ForInitContext ctx) { }
	@Override public void exitForInit(Java7Parser.ForInitContext ctx) { }
	@Override public void enterBound(Java7Parser.BoundContext ctx) { }
	@Override public void exitBound(Java7Parser.BoundContext ctx) { }
	@Override public void enterSelector(Java7Parser.SelectorContext ctx) { }
	@Override public void exitSelector(Java7Parser.SelectorContext ctx) { }
	@Override public void enterAnnotationTypeDeclaration(Java7Parser.AnnotationTypeDeclarationContext ctx) { }
	@Override public void exitAnnotationTypeDeclaration(Java7Parser.AnnotationTypeDeclarationContext ctx) { }
	@Override public void enterVariableDeclarator(Java7Parser.VariableDeclaratorContext ctx) { }
	@Override public void exitVariableDeclarator(Java7Parser.VariableDeclaratorContext ctx) { }
	@Override public void enterStatementFoundInBlock(Java7Parser.StatementFoundInBlockContext ctx) { }
	@Override public void exitStatementFoundInBlock(Java7Parser.StatementFoundInBlockContext ctx) { }
	@Override public void enterExpression(Java7Parser.ExpressionContext ctx) { }
	@Override public void exitExpression(Java7Parser.ExpressionContext ctx) { }
	@Override public void enterResources(Java7Parser.ResourcesContext ctx) { }
	@Override public void exitResources(Java7Parser.ResourcesContext ctx) { }
	@Override public void enterQualifiedIdentifier(Java7Parser.QualifiedIdentifierContext ctx) { }
	@Override public void exitQualifiedIdentifier(Java7Parser.QualifiedIdentifierContext ctx) { }
	@Override public void enterType(Java7Parser.TypeContext ctx) { }
	@Override public void exitType(Java7Parser.TypeContext ctx) { }
	@Override public void enterMemberDecl(Java7Parser.MemberDeclContext ctx) { }
	@Override public void exitMemberDecl(Java7Parser.MemberDeclContext ctx) { }
	@Override public void enterElementValueArrayInitializer(Java7Parser.ElementValueArrayInitializerContext ctx) { }
	@Override public void exitElementValueArrayInitializer(Java7Parser.ElementValueArrayInitializerContext ctx) { }
	@Override public void enterAnnotationMethodRest(Java7Parser.AnnotationMethodRestContext ctx) { }
	@Override public void exitAnnotationMethodRest(Java7Parser.AnnotationMethodRestContext ctx) { }
	@Override public void enterFormalParameterDeclsRest(Java7Parser.FormalParameterDeclsRestContext ctx) { }
	@Override public void exitFormalParameterDeclsRest(Java7Parser.FormalParameterDeclsRestContext ctx) { }
	@Override public void enterAnnotationTypeElementDeclarations(Java7Parser.AnnotationTypeElementDeclarationsContext ctx) { }
	@Override public void exitAnnotationTypeElementDeclarations(Java7Parser.AnnotationTypeElementDeclarationsContext ctx) { }
	@Override public void enterPrimary(Java7Parser.PrimaryContext ctx) { }
	@Override public void exitPrimary(Java7Parser.PrimaryContext ctx) { }
	@Override public void enterIdentifierSuffix(Java7Parser.IdentifierSuffixContext ctx) { }
	@Override public void exitIdentifierSuffix(Java7Parser.IdentifierSuffixContext ctx) { }
	@Override public void enterClassBody(Java7Parser.ClassBodyContext ctx) { }
	@Override public void exitClassBody(Java7Parser.ClassBodyContext ctx) { }
	@Override public void enterVariableModifier(Java7Parser.VariableModifierContext ctx) { }
	@Override public void exitVariableModifier(Java7Parser.VariableModifierContext ctx) { }
	@Override public void enterCreatedName(Java7Parser.CreatedNameContext ctx) { }
	@Override public void exitCreatedName(Java7Parser.CreatedNameContext ctx) { }
	@Override public void enterInterfaceDeclaration(Java7Parser.InterfaceDeclarationContext ctx) { }
	@Override public void exitInterfaceDeclaration(Java7Parser.InterfaceDeclarationContext ctx) { }
	@Override public void enterConstantDeclaratorRest(Java7Parser.ConstantDeclaratorRestContext ctx) { }
	@Override public void exitConstantDeclaratorRest(Java7Parser.ConstantDeclaratorRestContext ctx) { }
	@Override public void enterConstantDeclarator(Java7Parser.ConstantDeclaratorContext ctx) { }
	@Override public void exitConstantDeclarator(Java7Parser.ConstantDeclaratorContext ctx) { }
	@Override public void enterCatchType(Java7Parser.CatchTypeContext ctx) { }
	@Override public void exitCatchType(Java7Parser.CatchTypeContext ctx) { }
	@Override public void enterTypeArguments(Java7Parser.TypeArgumentsContext ctx) { }
	@Override public void exitTypeArguments(Java7Parser.TypeArgumentsContext ctx) { }
	@Override public void enterClassCreatorRest(Java7Parser.ClassCreatorRestContext ctx) { }
	@Override public void exitClassCreatorRest(Java7Parser.ClassCreatorRestContext ctx) { }
	@Override public void enterCatchFormalParameter(Java7Parser.CatchFormalParameterContext ctx) { }
	@Override public void exitCatchFormalParameter(Java7Parser.CatchFormalParameterContext ctx) { }
	@Override public void enterModifier(Java7Parser.ModifierContext ctx) { }
	@Override public void exitModifier(Java7Parser.ModifierContext ctx) { }
	@Override public void enterStatement(Java7Parser.StatementContext ctx) { }
	@Override public void exitStatement(Java7Parser.StatementContext ctx) { }
	@Override public void enterInterfaceBody(Java7Parser.InterfaceBodyContext ctx) { }
	@Override public void exitInterfaceBody(Java7Parser.InterfaceBodyContext ctx) { }
	@Override public void enterSwitchLabels(Java7Parser.SwitchLabelsContext ctx) { }
	@Override public void exitSwitchLabels(Java7Parser.SwitchLabelsContext ctx) { }
	@Override public void enterClassBodyDeclaration(Java7Parser.ClassBodyDeclarationContext ctx) { }
	@Override public void exitClassBodyDeclaration(Java7Parser.ClassBodyDeclarationContext ctx) { }
	@Override public void enterForControl(Java7Parser.ForControlContext ctx) { }
	@Override public void exitForControl(Java7Parser.ForControlContext ctx) { }
	@Override public void enterTypeList(Java7Parser.TypeListContext ctx) { }
	@Override public void exitTypeList(Java7Parser.TypeListContext ctx) { }
	@Override public void enterAssignmentOperator(Java7Parser.AssignmentOperatorContext ctx) { }
	@Override public void exitAssignmentOperator(Java7Parser.AssignmentOperatorContext ctx) { }
	@Override public void enterVariableDeclaratorId(Java7Parser.VariableDeclaratorIdContext ctx) { }
	@Override public void exitVariableDeclaratorId(Java7Parser.VariableDeclaratorIdContext ctx) { }
	@Override public void enterElementValue(Java7Parser.ElementValueContext ctx) { }
	@Override public void exitElementValue(Java7Parser.ElementValueContext ctx) { }
	@Override public void enterCompilationUnit(Java7Parser.CompilationUnitContext ctx) { }
	@Override public void exitCompilationUnit(Java7Parser.CompilationUnitContext ctx) { }
	@Override public void enterTypeArgumentsOrDiamond(Java7Parser.TypeArgumentsOrDiamondContext ctx) { }
	@Override public void exitTypeArgumentsOrDiamond(Java7Parser.TypeArgumentsOrDiamondContext ctx) { }
	@Override public void enterAnnotationTypeElementDeclaration(Java7Parser.AnnotationTypeElementDeclarationContext ctx) { }
	@Override public void exitAnnotationTypeElementDeclaration(Java7Parser.AnnotationTypeElementDeclarationContext ctx) { }
	@Override public void enterBlockStatement(Java7Parser.BlockStatementContext ctx) { }
	@Override public void exitBlockStatement(Java7Parser.BlockStatementContext ctx) { }
	@Override public void enterAnnotationTypeBody(Java7Parser.AnnotationTypeBodyContext ctx) { }
	@Override public void exitAnnotationTypeBody(Java7Parser.AnnotationTypeBodyContext ctx) { }
	@Override public void enterIntegerLiteral(Java7Parser.IntegerLiteralContext ctx) { }
	@Override public void exitIntegerLiteral(Java7Parser.IntegerLiteralContext ctx) { }
	@Override public void enterInterfaceMemberDecl(Java7Parser.InterfaceMemberDeclContext ctx) { }
	@Override public void exitInterfaceMemberDecl(Java7Parser.InterfaceMemberDeclContext ctx) { }
	@Override public void enterCreator(Java7Parser.CreatorContext ctx) { }
	@Override public void exitCreator(Java7Parser.CreatorContext ctx) { }
	@Override public void enterInterfaceGenericMethodDecl(Java7Parser.InterfaceGenericMethodDeclContext ctx) { }
	@Override public void exitInterfaceGenericMethodDecl(Java7Parser.InterfaceGenericMethodDeclContext ctx) { }
	@Override public void enterReferenceType(Java7Parser.ReferenceTypeContext ctx) { }
	@Override public void exitReferenceType(Java7Parser.ReferenceTypeContext ctx) { }
	@Override public void enterFormalParameterDecls(Java7Parser.FormalParameterDeclsContext ctx) { }
	@Override public void exitFormalParameterDecls(Java7Parser.FormalParameterDeclsContext ctx) { }
	@Override public void enterVoidMethodDeclaratorRest(Java7Parser.VoidMethodDeclaratorRestContext ctx) { }
	@Override public void exitVoidMethodDeclaratorRest(Java7Parser.VoidMethodDeclaratorRestContext ctx) { }
	@Override public void enterAnnotationTypeElementRest(Java7Parser.AnnotationTypeElementRestContext ctx) { }
	@Override public void exitAnnotationTypeElementRest(Java7Parser.AnnotationTypeElementRestContext ctx) { }
	@Override public void enterResourceSpecification(Java7Parser.ResourceSpecificationContext ctx) { }
	@Override public void exitResourceSpecification(Java7Parser.ResourceSpecificationContext ctx) { }
	@Override public void enterForVariableDeclaratorsRest(Java7Parser.ForVariableDeclaratorsRestContext ctx) { }
	@Override public void exitForVariableDeclaratorsRest(Java7Parser.ForVariableDeclaratorsRestContext ctx) { }
	@Override public void enterForVarControlRest(Java7Parser.ForVarControlRestContext ctx) { }
	@Override public void exitForVarControlRest(Java7Parser.ForVarControlRestContext ctx) { }
	@Override public void enterAnnotationElement(Java7Parser.AnnotationElementContext ctx) { }
	@Override public void exitAnnotationElement(Java7Parser.AnnotationElementContext ctx) { }
	@Override public void enterResource(Java7Parser.ResourceContext ctx) { }
	@Override public void exitResource(Java7Parser.ResourceContext ctx) { }
	@Override public void enterElementValuePair(Java7Parser.ElementValuePairContext ctx) { }
	@Override public void exitElementValuePair(Java7Parser.ElementValuePairContext ctx) { }
	@Override public void enterVoidInterfaceMethodDeclaratorRest(Java7Parser.VoidInterfaceMethodDeclaratorRestContext ctx) { }
	@Override public void exitVoidInterfaceMethodDeclaratorRest(Java7Parser.VoidInterfaceMethodDeclaratorRestContext ctx) { }
	@Override public void enterClassType(Java7Parser.ClassTypeContext ctx) { }
	@Override public void exitClassType(Java7Parser.ClassTypeContext ctx) { }
	@Override public void enterGenericMethodOrConstructorRest(Java7Parser.GenericMethodOrConstructorRestContext ctx) { }
	@Override public void exitGenericMethodOrConstructorRest(Java7Parser.GenericMethodOrConstructorRestContext ctx) { }
	@Override public void enterInterfaceMethodOrFieldRest(Java7Parser.InterfaceMethodOrFieldRestContext ctx) { }
	@Override public void exitInterfaceMethodOrFieldRest(Java7Parser.InterfaceMethodOrFieldRestContext ctx) { }
	@Override public void enterVariableDeclaratorRest(Java7Parser.VariableDeclaratorRestContext ctx) { }
	@Override public void exitVariableDeclaratorRest(Java7Parser.VariableDeclaratorRestContext ctx) { }
	@Override public void enterArrayInitializer(Java7Parser.ArrayInitializerContext ctx) { }
	@Override public void exitArrayInitializer(Java7Parser.ArrayInitializerContext ctx) { }
	@Override public void enterNonWildcardTypeArgumentsOrDiamond(Java7Parser.NonWildcardTypeArgumentsOrDiamondContext ctx) { }
	@Override public void exitNonWildcardTypeArgumentsOrDiamond(Java7Parser.NonWildcardTypeArgumentsOrDiamondContext ctx) { }
	@Override public void enterVariableModifiers(Java7Parser.VariableModifiersContext ctx) { }
	@Override public void exitVariableModifiers(Java7Parser.VariableModifiersContext ctx) { }
	@Override public void enterNonWildcardTypeArguments(Java7Parser.NonWildcardTypeArgumentsContext ctx) { }
	@Override public void exitNonWildcardTypeArguments(Java7Parser.NonWildcardTypeArgumentsContext ctx) { }
	@Override public void enterClassOrInterfaceDeclaration(Java7Parser.ClassOrInterfaceDeclarationContext ctx) { }
	@Override public void exitClassOrInterfaceDeclaration(Java7Parser.ClassOrInterfaceDeclarationContext ctx) { }
	@Override public void enterBasicType(Java7Parser.BasicTypeContext ctx) { }
	@Override public void exitBasicType(Java7Parser.BasicTypeContext ctx) { }
	@Override public void enterArrayCreatorRest(Java7Parser.ArrayCreatorRestContext ctx) { }
	@Override public void exitArrayCreatorRest(Java7Parser.ArrayCreatorRestContext ctx) { }
	@Override public void enterLiteral(Java7Parser.LiteralContext ctx) { }
	@Override public void exitLiteral(Java7Parser.LiteralContext ctx) { }
	@Override public void enterMethodOrFieldRest(Java7Parser.MethodOrFieldRestContext ctx) { }
	@Override public void exitMethodOrFieldRest(Java7Parser.MethodOrFieldRestContext ctx) { }
	@Override public void enterSwitchBlockStatementGroup(Java7Parser.SwitchBlockStatementGroupContext ctx) { }
	@Override public void exitSwitchBlockStatementGroup(Java7Parser.SwitchBlockStatementGroupContext ctx) { }

	@Override public void enterEveryRule(ParserRuleContext ctx) { }
	@Override public void exitEveryRule(ParserRuleContext ctx) { }
	@Override public void visitTerminal(TerminalNode node) { }
	@Override public void visitErrorNode(ErrorNode node) { }
}